#!/usr/bin/ansible-playbook

### Создайте плейбук для изменения файла /etc/default/grub. 
# Он должен добавить параметры net.ifnames=0 и biosdevname=0 в строку, 
# выполняющую загрузку ядра. 
# Выполните grub2-mkconfig, чтобы записать изменения в /etc/default/grub. 
# Используйте модуль lineinfile для изменения конфигурационного файла.


---
- name: homework 1.1.3
  hosts: webservers
  become: yes
  become_user: root

  tasks:

##### this breaks start of networking
##  - name: switch on NetworkManager
##    systemd:
##      name: NetworkManager
##      state: started
##      enabled: yes
####      state: stopped
####      enabled: no

  - name: change grub - check
    shell: |
      grep -P "net.ifnames=.*biosdevname=|biosdevname=.*net.ifnames=" /etc/default/grub
    register: grub_has_items
    ignore_errors: True
    changed_when: False

  - name: change grub - edit
    when: grub_has_items.rc > 0
    lineinfile:
      path: /etc/default/grub
      regexp: ^\s*GRUB_CMDLINE_LINUX=\"*([^"]*)\"*
##"
      backrefs: yes
      line: GRUB_CMDLINE_LINUX="\g<1> net.ifnames=0 biosdevname=0"
      backup: yes

  - name: change grub - apply
    shell: |
      grub2-mkconfig -o /boot/grub2/grub.cfg
