#!/usr/bin/ansible-playbook

###     1. Создайте плэйбук, выполняющий установку веб-сервера Apache на управляемом хосте со следующими требованиями:
#    • установка пакета httpd;
#    • включение службы веб-сервера и проверка, что он запущен;
#    • создание файла /var/www/html/index.html с текстом “Welcome to my web server”;
#    • используйте модуль firewalld для того, чтобы открыть необходимые для работы веб-сервера порты брендмауэра.

---
- name: homework 1.1.1
  hosts: webservers
  become: yes
  become_user: root

  tasks:

  - name: install httpd
    package: 
      name: 
        - httpd
      state: latest

  - name: keep folder /var/www/html/index.html
    file:
      dest: /var/www/html
      state: directory

  - name: create index.html
    copy:
      dest: /var/www/html/index.html
      content: |
        Welcome to my web server!
        {{ansible_all_ipv4_addresses}}
        {{ansible_date_time.iso8601}}
    notify: restart httpd

  - name: run firewall
    service:
      name: "firewalld"
      state: started

  - name: setup firewall
    firewalld:
      service: "{{item}}"
      state: enabled    
      permanent: yes
      immediate: yes
    with_items:
      - http
      - https



  handlers:

  - name: restart httpd
    service: 
      name:  httpd
      state: restarted
